apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Subhradeep Workflow 2
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  subhradeep-job-1:
    steps:
      - name: Subhradeep Step 2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Subhradeep Message 2"
