apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Subhradeep Workflow B
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  subhradeep-job-1:
    steps:
      - name: Subhradeep Step B
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Subhradeep Message B"
