apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: push-when-error-test-workflow

on:
  push:
    branches: [ main ]

jobs:
  test-push-when-expression-error:
    runs-on: cloudbees-runner
    steps:
      - name: Setup context
        uses: cloudbees-io/configure-oidc-tokens@v1
        with:
          audience: test-audience
          
      - name: Action with invalid when condition
        id: push-when-error-step
        uses: docker://alpine:latest
        # This will cause push.go to fail during evaluateStepSkip
        # because 'invalid' is not available in the scope
        if: ${{ invalid.when.condition }}
        with:
          valid_input: "test-value"
          run: |
            echo "This action should not execute due to when condition evaluation error"
            echo "valid_input: ${{ valid_input }}"
            
      - name: Fallback step that should still run
        uses: docker://alpine:latest
        with:
          run: |
            echo "This step should run if the workflow continues after the error"
